//@version=5
strategy("Null Strategy", overlay=true, pyramiding=300000)

/// INPUTS
// Define our inputs
SYMBOL = input.string(defval="AUDUSD", title="Select Main Source Symbol", options=["AUDUSD", "AUDCNH", "AUDJPY", "AUDGBP", "AUDEUR", "AUDCAD", "AUDCHF", "AUDNZD", "USDEUR", "USDCNH", "USDJPY", "USDGBP", "USDAUD", "USDCAD", "USDCHF", "USDNZD", "EURUSD", "EURCNH", "EURJPY", "EURGBP", "EURAUD", "EURCAD", "EURCHF", "EURNZD", "SPX500", "EURO50", "AUS200", "XAUUSD", "WTIOIL", "USDIDX", "EURIDX", "AUDIDX"])

stop_loss_percent   = input.float(defval=0.1, step=0.01, title="Stop Loss (%)")   / 100
take_profit_percent = input.float(defval=0.1, step=0.01, title="Take Profit (%)") / 100

// Calculate our stop loss and take profit levels
long_sl = strategy.position_avg_price * (1 - stop_loss_percent)
long_tp = strategy.position_avg_price * (1 + take_profit_percent)
short_stop = close * (1 + stop_loss_percent)
short_tp   = close * (1 - take_profit_percent)

// Submit our orders
strategy.entry(id="EnterLong",  direction=strategy.long)

strategy.entry(id="Short", direction=strategy.short)

// Submit exit orders based on calculated stop loss price
if (strategy.position_size > 0)
    strategy.exit(id="ExitLong",  stop=long_sl,  limit=long_tp)

if (strategy.position_size < 0)
    strategy.exit(id="ExitShort", stop=short_stop, limit=short_tp)