cd /home/selknam/dev/rata/src 
source /home/selknam/opt/miniconda3/bin/activate rata.py39 
sleep 180 ; python3 -u predict_catboost.py --db_host=192.168.3.113 --symbol=EURUSD --interval=3 --shift=3 --X_symbols=EURUSD --X_include=rsi,* --X_exclude=volatility_kcli --nrows=3000 --test_lenght=nn --iterations=nn --learning_rate=nn --depth=nn --l2_leaf_reg=nn --loss_function=RMSE & 
sleep 180 ; python3 -u predict_catboost.py --db_host=192.168.3.113 --symbol=EURUSD --interval=1 --shift=1 --X_symbols=EURUSD --X_include=rsi,* --X_exclude=volatility_kcli --nrows=3000 --test_lenght=nn --iterations=nn --learning_rate=nn --depth=nn --l2_leaf_reg=nn --loss_function=MAPE & 
sleep 180 ; python3 -u predict_catboost.py --db_host=192.168.3.113 --symbol=EURUSD --interval=1 --shift=9 --X_symbols=EURUSD --X_include=rsi,* --X_exclude=volatility_kcli --nrows=3000 --test_lenght=nn --iterations=nn --learning_rate=nn --depth=nn --l2_leaf_reg=nn --loss_function=RMSE & 
sleep 180 ; python3 -u predict_catboost.py --db_host=192.168.3.113 --symbol=EURUSD --interval=1 --shift=9 --X_symbols=EURUSD --X_include=rsi,* --X_exclude=volatility_kcli --nrows=3000 --test_lenght=nn --iterations=nn --learning_rate=nn --depth=nn --l2_leaf_reg=nn --loss_function=MAPE & 
sleep 180 ; python3 -u predict_catboost.py --db_host=192.168.3.113 --symbol=EURUSD --interval=1 --shift=3 --X_symbols=EURUSD --X_include=rsi,* --X_exclude=volatility_kcli --nrows=3000 --test_lenght=nn --iterations=nn --learning_rate=nn --depth=nn --l2_leaf_reg=nn --loss_function=MAPE & 
sleep 180 ; python3 -u predict_catboost.py --db_host=192.168.3.113 --symbol=EURUSD --interval=3 --shift=6 --X_symbols=EURUSD --X_include=rsi,* --X_exclude=volatility_kcli --nrows=3000 --test_lenght=nn --iterations=nn --learning_rate=nn --depth=nn --l2_leaf_reg=nn --loss_function=RMSE & 
sleep 180 ; python3 -u predict_catboost.py --db_host=192.168.3.113 --symbol=EURUSD --interval=1 --shift=3 --X_symbols=EURUSD --X_include=rsi,* --X_exclude=volatility_kcli --nrows=3000 --test_lenght=nn --iterations=nn --learning_rate=nn --depth=nn --l2_leaf_reg=nn --loss_function=RMSE & 
sleep 180 ; python3 -u predict_catboost.py --db_host=192.168.3.113 --symbol=EURUSD --interval=3 --shift=1 --X_symbols=EURUSD --X_include=rsi,* --X_exclude=volatility_kcli --nrows=3000 --test_lenght=nn --iterations=nn --learning_rate=nn --depth=nn --l2_leaf_reg=nn --loss_function=MAPE & 
sleep 180 ; python3 -u predict_catboost.py --db_host=192.168.3.113 --symbol=EURUSD --interval=3 --shift=9 --X_symbols=EURUSD --X_include=rsi,* --X_exclude=volatility_kcli --nrows=3000 --test_lenght=nn --iterations=nn --learning_rate=nn --depth=nn --l2_leaf_reg=nn --loss_function=MAPE & 
sleep 180 ; python3 -u predict_catboost.py --db_host=192.168.3.113 --symbol=EURUSD --interval=3 --shift=6 --X_symbols=EURUSD --X_include=rsi,* --X_exclude=volatility_kcli --nrows=3000 --test_lenght=nn --iterations=nn --learning_rate=nn --depth=nn --l2_leaf_reg=nn --loss_function=MAPE & 
sleep 180 ; python3 -u predict_catboost.py --db_host=192.168.3.113 --symbol=EURUSD --interval=3 --shift=9 --X_symbols=EURUSD --X_include=rsi,* --X_exclude=volatility_kcli --nrows=3000 --test_lenght=nn --iterations=nn --learning_rate=nn --depth=nn --l2_leaf_reg=nn --loss_function=RMSE & 
sleep 180 ; python3 -u predict_catboost.py --db_host=192.168.3.113 --symbol=EURUSD --interval=1 --shift=6 --X_symbols=EURUSD --X_include=rsi,* --X_exclude=volatility_kcli --nrows=3000 --test_lenght=nn --iterations=nn --learning_rate=nn --depth=nn --l2_leaf_reg=nn --loss_function=RMSE & 
sleep 180 ; python3 -u predict_catboost.py --db_host=192.168.3.113 --symbol=EURUSD --interval=1 --shift=6 --X_symbols=EURUSD --X_include=rsi,* --X_exclude=volatility_kcli --nrows=3000 --test_lenght=nn --iterations=nn --learning_rate=nn --depth=nn --l2_leaf_reg=nn --loss_function=MAPE & 
sleep 180 ; python3 -u predict_catboost.py --db_host=192.168.3.113 --symbol=EURUSD --interval=1 --shift=1 --X_symbols=EURUSD --X_include=rsi,* --X_exclude=volatility_kcli --nrows=3000 --test_lenght=nn --iterations=nn --learning_rate=nn --depth=nn --l2_leaf_reg=nn --loss_function=RMSE & 
sleep 180 ; python3 -u predict_catboost.py --db_host=192.168.3.113 --symbol=EURUSD --interval=3 --shift=1 --X_symbols=EURUSD --X_include=rsi,* --X_exclude=volatility_kcli --nrows=3000 --test_lenght=nn --iterations=nn --learning_rate=nn --depth=nn --l2_leaf_reg=nn --loss_function=RMSE & 
sleep 180 ; python3 -u predict_catboost.py --db_host=192.168.3.113 --symbol=EURUSD --interval=3 --shift=3 --X_symbols=EURUSD --X_include=rsi,* --X_exclude=volatility_kcli --nrows=3000 --test_lenght=nn --iterations=nn --learning_rate=nn --depth=nn --l2_leaf_reg=nn --loss_function=MAPE & 