python3 rates-get-old.py --db_host=localhost --symbol=NZDUSD --kind=forex --interval=1 --tstamp=2022-04-01
python3 rates-get-old.py --db_host=localhost --symbol=NZDUSD --kind=forex --interval=1 --tstamp=2022-04-02
python3 rates-get-old.py --db_host=localhost --symbol=NZDUSD --kind=forex --interval=1 --tstamp=2022-04-03
python3 rates-get-old.py --db_host=localhost --symbol=NZDUSD --kind=forex --interval=1 --tstamp=2022-04-04
python3 rates-get-old.py --db_host=localhost --symbol=NZDUSD --kind=forex --interval=1 --tstamp=2022-04-05
python3 rates-get-old.py --db_host=localhost --symbol=NZDUSD --kind=forex --interval=1 --tstamp=2022-04-06
python3 rates-get-old.py --db_host=localhost --symbol=NZDUSD --kind=forex --interval=1 --tstamp=2022-04-07
python3 rates-get-old.py --db_host=localhost --symbol=NZDUSD --kind=forex --interval=1 --tstamp=2022-04-08
python3 rates-get-old.py --db_host=localhost --symbol=NZDUSD --kind=forex --interval=1 --tstamp=2022-04-09
python3 rates-get-old.py --db_host=localhost --symbol=NZDUSD --kind=forex --interval=1 --tstamp=2022-04-10
python3 rates-get-old.py --db_host=localhost --symbol=NZDUSD --kind=forex --interval=1 --tstamp=2022-04-11
python3 rates-get-old.py --db_host=localhost --symbol=NZDUSD --kind=forex --interval=1 --tstamp=2022-04-12
python3 rates-get-old.py --db_host=localhost --symbol=NZDUSD --kind=forex --interval=1 --tstamp=2022-04-13
python3 rates-get-old.py --db_host=localhost --symbol=NZDUSD --kind=forex --interval=1 --tstamp=2022-04-14
python3 rates-get-old.py --db_host=localhost --symbol=NZDUSD --kind=forex --interval=1 --tstamp=2022-04-15
python3 rates-get-old.py --db_host=localhost --symbol=NZDUSD --kind=forex --interval=1 --tstamp=2022-04-16
python3 rates-get-old.py --db_host=localhost --symbol=NZDUSD --kind=forex --interval=1 --tstamp=2022-04-17
python3 rates-get-old.py --db_host=localhost --symbol=NZDUSD --kind=forex --interval=1 --tstamp=2022-04-18
python3 rates-get-old.py --db_host=localhost --symbol=NZDUSD --kind=forex --interval=1 --tstamp=2022-04-19
python3 rates-get-old.py --db_host=localhost --symbol=NZDUSD --kind=forex --interval=1 --tstamp=2022-04-20
python3 rates-get-old.py --db_host=localhost --symbol=NZDUSD --kind=forex --interval=1 --tstamp=2022-04-21
python3 rates-get-old.py --db_host=localhost --symbol=NZDUSD --kind=forex --interval=1 --tstamp=2022-04-22
python3 rates-get-old.py --db_host=localhost --symbol=NZDUSD --kind=forex --interval=1 --tstamp=2022-04-23
python3 rates-get-old.py --db_host=localhost --symbol=NZDUSD --kind=forex --interval=1 --tstamp=2022-04-24
python3 rates-get-old.py --db_host=localhost --symbol=NZDUSD --kind=forex --interval=1 --tstamp=2022-04-25
python3 rates-get-old.py --db_host=localhost --symbol=NZDUSD --kind=forex --interval=1 --tstamp=2022-04-26
python3 rates-get-old.py --db_host=localhost --symbol=NZDUSD --kind=forex --interval=1 --tstamp=2022-04-27
python3 rates-get-old.py --db_host=localhost --symbol=NZDUSD --kind=forex --interval=1 --tstamp=2022-04-28
python3 rates-get-old.py --db_host=localhost --symbol=NZDUSD --kind=forex --interval=1 --tstamp=2022-04-29
python3 rates-get-old.py --db_host=localhost --symbol=NZDUSD --kind=forex --interval=1 --tstamp=2022-04-30

python3 rates-get-old.py --db_host=localhost --symbol=NZDUSD --kind=forex --interval=1 --tstamp=2022-05-01
python3 rates-get-old.py --db_host=localhost --symbol=NZDUSD --kind=forex --interval=1 --tstamp=2022-05-02
python3 rates-get-old.py --db_host=localhost --symbol=NZDUSD --kind=forex --interval=1 --tstamp=2022-05-03
python3 rates-get-old.py --db_host=localhost --symbol=NZDUSD --kind=forex --interval=1 --tstamp=2022-05-04
python3 rates-get-old.py --db_host=localhost --symbol=NZDUSD --kind=forex --interval=1 --tstamp=2022-05-05
python3 rates-get-old.py --db_host=localhost --symbol=NZDUSD --kind=forex --interval=1 --tstamp=2022-05-06
python3 rates-get-old.py --db_host=localhost --symbol=NZDUSD --kind=forex --interval=1 --tstamp=2022-05-07
python3 rates-get-old.py --db_host=localhost --symbol=NZDUSD --kind=forex --interval=1 --tstamp=2022-05-08
python3 rates-get-old.py --db_host=localhost --symbol=NZDUSD --kind=forex --interval=1 --tstamp=2022-05-09
python3 rates-get-old.py --db_host=localhost --symbol=NZDUSD --kind=forex --interval=1 --tstamp=2022-05-10
python3 rates-get-old.py --db_host=localhost --symbol=NZDUSD --kind=forex --interval=1 --tstamp=2022-05-11
python3 rates-get-old.py --db_host=localhost --symbol=NZDUSD --kind=forex --interval=1 --tstamp=2022-05-12
python3 rates-get-old.py --db_host=localhost --symbol=NZDUSD --kind=forex --interval=1 --tstamp=2022-05-13
python3 rates-get-old.py --db_host=localhost --symbol=NZDUSD --kind=forex --interval=1 --tstamp=2022-05-14
python3 rates-get-old.py --db_host=localhost --symbol=NZDUSD --kind=forex --interval=1 --tstamp=2022-05-15
python3 rates-get-old.py --db_host=localhost --symbol=NZDUSD --kind=forex --interval=1 --tstamp=2022-05-16
python3 rates-get-old.py --db_host=localhost --symbol=NZDUSD --kind=forex --interval=1 --tstamp=2022-05-17
python3 rates-get-old.py --db_host=localhost --symbol=NZDUSD --kind=forex --interval=1 --tstamp=2022-05-18
python3 rates-get-old.py --db_host=localhost --symbol=NZDUSD --kind=forex --interval=1 --tstamp=2022-05-19
python3 rates-get-old.py --db_host=localhost --symbol=NZDUSD --kind=forex --interval=1 --tstamp=2022-05-20
python3 rates-get-old.py --db_host=localhost --symbol=NZDUSD --kind=forex --interval=1 --tstamp=2022-05-21
python3 rates-get-old.py --db_host=localhost --symbol=NZDUSD --kind=forex --interval=1 --tstamp=2022-05-22
python3 rates-get-old.py --db_host=localhost --symbol=NZDUSD --kind=forex --interval=1 --tstamp=2022-05-23
python3 rates-get-old.py --db_host=localhost --symbol=NZDUSD --kind=forex --interval=1 --tstamp=2022-05-24
python3 rates-get-old.py --db_host=localhost --symbol=NZDUSD --kind=forex --interval=1 --tstamp=2022-05-25
python3 rates-get-old.py --db_host=localhost --symbol=NZDUSD --kind=forex --interval=1 --tstamp=2022-05-26
python3 rates-get-old.py --db_host=localhost --symbol=NZDUSD --kind=forex --interval=1 --tstamp=2022-05-27


python3 rates-get-old.py --db_host=localhost --symbol=NZDUSD --kind=forex --interval=1 --tstamp=2022-06-10
python3 rates-get-old.py --db_host=localhost --symbol=NZDUSD --kind=forex --interval=1 --tstamp=2022-06-11
python3 rates-get-old.py --db_host=localhost --symbol=NZDUSD --kind=forex --interval=1 --tstamp=2022-06-12
python3 rates-get-old.py --db_host=localhost --symbol=NZDUSD --kind=forex --interval=1 --tstamp=2022-06-13
python3 rates-get-old.py --db_host=localhost --symbol=NZDUSD --kind=forex --interval=1 --tstamp=2022-06-14
python3 rates-get-old.py --db_host=localhost --symbol=NZDUSD --kind=forex --interval=1 --tstamp=2022-06-15
python3 rates-get-old.py --db_host=localhost --symbol=NZDUSD --kind=forex --interval=1 --tstamp=2022-06-16
python3 rates-get-old.py --db_host=localhost --symbol=NZDUSD --kind=forex --interval=1 --tstamp=2022-06-17

python3 rates-get-old.py --db_host=localhost --symbol=EURGBP --kind=forex --interval=1 --tstamp=2022-06-10
python3 rates-get-old.py --db_host=localhost --symbol=EURGBP --kind=forex --interval=1 --tstamp=2022-06-11
python3 rates-get-old.py --db_host=localhost --symbol=EURGBP --kind=forex --interval=1 --tstamp=2022-06-12
python3 rates-get-old.py --db_host=localhost --symbol=EURGBP --kind=forex --interval=1 --tstamp=2022-06-13
python3 rates-get-old.py --db_host=localhost --symbol=EURGBP --kind=forex --interval=1 --tstamp=2022-06-14
python3 rates-get-old.py --db_host=localhost --symbol=EURGBP --kind=forex --interval=1 --tstamp=2022-06-15
python3 rates-get-old.py --db_host=localhost --symbol=EURGBP --kind=forex --interval=1 --tstamp=2022-06-16
python3 rates-get-old.py --db_host=localhost --symbol=EURGBP --kind=forex --interval=1 --tstamp=2022-06-17

python3 rates-get-old.py --db_host=localhost --symbol=GBPNZD --kind=forex --interval=1 --tstamp=2022-06-10
python3 rates-get-old.py --db_host=localhost --symbol=GBPNZD --kind=forex --interval=1 --tstamp=2022-06-11
python3 rates-get-old.py --db_host=localhost --symbol=GBPNZD --kind=forex --interval=1 --tstamp=2022-06-12
python3 rates-get-old.py --db_host=localhost --symbol=GBPNZD --kind=forex --interval=1 --tstamp=2022-06-13
python3 rates-get-old.py --db_host=localhost --symbol=GBPNZD --kind=forex --interval=1 --tstamp=2022-06-14
python3 rates-get-old.py --db_host=localhost --symbol=GBPNZD --kind=forex --interval=1 --tstamp=2022-06-15
python3 rates-get-old.py --db_host=localhost --symbol=GBPNZD --kind=forex --interval=1 --tstamp=2022-06-16
python3 rates-get-old.py --db_host=localhost --symbol=GBPNZD --kind=forex --interval=1 --tstamp=2022-06-17

python3 rates-get-old.py --db_host=localhost --symbol=AUDNZD --kind=forex --interval=1 --tstamp=2022-06-10
python3 rates-get-old.py --db_host=localhost --symbol=AUDNZD --kind=forex --interval=1 --tstamp=2022-06-11
python3 rates-get-old.py --db_host=localhost --symbol=AUDNZD --kind=forex --interval=1 --tstamp=2022-06-12
python3 rates-get-old.py --db_host=localhost --symbol=AUDNZD --kind=forex --interval=1 --tstamp=2022-06-13
python3 rates-get-old.py --db_host=localhost --symbol=AUDNZD --kind=forex --interval=1 --tstamp=2022-06-14
python3 rates-get-old.py --db_host=localhost --symbol=AUDNZD --kind=forex --interval=1 --tstamp=2022-06-15
python3 rates-get-old.py --db_host=localhost --symbol=AUDNZD --kind=forex --interval=1 --tstamp=2022-06-16
python3 rates-get-old.py --db_host=localhost --symbol=AUDNZD --kind=forex --interval=1 --tstamp=2022-06-17

python3 rates-get-old.py --db_host=localhost --symbol=AUDCHF --kind=forex --interval=1 --tstamp=2022-06-10
python3 rates-get-old.py --db_host=localhost --symbol=AUDCHF --kind=forex --interval=1 --tstamp=2022-06-11
python3 rates-get-old.py --db_host=localhost --symbol=AUDCHF --kind=forex --interval=1 --tstamp=2022-06-12
python3 rates-get-old.py --db_host=localhost --symbol=AUDCHF --kind=forex --interval=1 --tstamp=2022-06-13
python3 rates-get-old.py --db_host=localhost --symbol=AUDCHF --kind=forex --interval=1 --tstamp=2022-06-14
python3 rates-get-old.py --db_host=localhost --symbol=AUDCHF --kind=forex --interval=1 --tstamp=2022-06-15
python3 rates-get-old.py --db_host=localhost --symbol=AUDCHF --kind=forex --interval=1 --tstamp=2022-06-16
python3 rates-get-old.py --db_host=localhost --symbol=AUDCHF --kind=forex --interval=1 --tstamp=2022-06-17

python3 rates-get-old.py --db_host=localhost --symbol=GBPAUD --kind=forex --interval=1 --tstamp=2022-06-10
python3 rates-get-old.py --db_host=localhost --symbol=GBPAUD --kind=forex --interval=1 --tstamp=2022-06-11
python3 rates-get-old.py --db_host=localhost --symbol=GBPAUD --kind=forex --interval=1 --tstamp=2022-06-12
python3 rates-get-old.py --db_host=localhost --symbol=GBPAUD --kind=forex --interval=1 --tstamp=2022-06-13
python3 rates-get-old.py --db_host=localhost --symbol=GBPAUD --kind=forex --interval=1 --tstamp=2022-06-14
python3 rates-get-old.py --db_host=localhost --symbol=GBPAUD --kind=forex --interval=1 --tstamp=2022-06-15
python3 rates-get-old.py --db_host=localhost --symbol=GBPAUD --kind=forex --interval=1 --tstamp=2022-06-16
python3 rates-get-old.py --db_host=localhost --symbol=GBPAUD --kind=forex --interval=1 --tstamp=2022-06-17

python3 rates-get-old.py --db_host=localhost --symbol=AUDUSD --kind=forex --interval=1 --tstamp=2022-06-10
python3 rates-get-old.py --db_host=localhost --symbol=AUDUSD --kind=forex --interval=1 --tstamp=2022-06-11
python3 rates-get-old.py --db_host=localhost --symbol=AUDUSD --kind=forex --interval=1 --tstamp=2022-06-12
python3 rates-get-old.py --db_host=localhost --symbol=AUDUSD --kind=forex --interval=1 --tstamp=2022-06-13
python3 rates-get-old.py --db_host=localhost --symbol=AUDUSD --kind=forex --interval=1 --tstamp=2022-06-14
python3 rates-get-old.py --db_host=localhost --symbol=AUDUSD --kind=forex --interval=1 --tstamp=2022-06-15
python3 rates-get-old.py --db_host=localhost --symbol=AUDUSD --kind=forex --interval=1 --tstamp=2022-06-16
python3 rates-get-old.py --db_host=localhost --symbol=AUDUSD --kind=forex --interval=1 --tstamp=2022-06-17
